# Generated by Django 5.1.15 on 2026-04-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEscaneoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('MOVIL', 'Movil (cliente)'), ('CAJA', 'Caja (vendedor)')], max_length=10)),
                ('resultado', models.CharField(choices=[('OK', 'Reconocido'), ('NO_DETECTADO', 'No detecto'), ('DESCONOCIDO', 'Producto desconocido'), ('SKU_NO_EXISTE', 'SKU devuelto no existe en BD'), ('ERROR', 'Error de servicio')], max_length=15)),
                ('confianza', models.FloatField(blank=True, null=True)),
                ('latencia_ms', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de escaneo IA',
                'verbose_name_plural': 'Logs de escaneo IA',
                'ordering': ['-fecha'],
            },
        ),
    ]
