# Generated by Django 5.1.15 on 2026-04-30 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ia_service', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logescaneoia',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escaneos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='logescaneoia',
            index=models.Index(fields=['-fecha'], name='log_ia_fecha_idx'),
        ),
    ]
