# Generated by Django 5.1.15 on 2026-07-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoverificacion2fa',
            name='codigo',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='tokenrecuperacionpassword',
            name='codigo',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='tokenrecuperacionpassword',
            constraint=models.UniqueConstraint(condition=models.Q(('usado', False)), fields=('usuario', 'codigo'), name='unique_token_reset_activo_por_usuario'),
        ),
    ]
