# Generated by Django 5.1.15 on 2026-08-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp_hash_y_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='es_demo',
            field=models.BooleanField(db_index=True, default=False, help_text='Cuenta de demostracion: omite la verificacion 2FA de 6 digitos al iniciar sesion.', verbose_name='Cuenta demo'),
        ),
    ]
