# Generated by Django 5.1.15 on 2026-04-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoFCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_fcm', models.CharField(max_length=500, unique=True)),
                ('plataforma', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('registrado', models.DateTimeField(auto_now_add=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispositivo FCM',
                'verbose_name_plural': 'Dispositivos FCM',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPRA_EXITOSA', 'Compra exitosa'), ('OFERTA', 'Oferta'), ('STOCK_DISPONIBLE', 'Producto favorito disponible'), ('SISTEMA', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Payload extra (ej: boleta_id para deep linking).')),
                ('leida', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
