# Generated by Django 5.1.15 on 2026-04-30 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivofcm',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_fcm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dispositivofcm',
            index=models.Index(condition=models.Q(('activo', True)), fields=['usuario'], name='fcm_usuario_activo_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(condition=models.Q(('leida', False)), fields=['usuario', '-fecha_envio'], name='notif_usuario_no_leidas_idx'),
        ),
    ]
