# Generated by Django 5.1.6 on 2026-06-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivofcm',
            name='plataforma',
            field=models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], max_length=10),
        ),
    ]
