# Generated by Django 5.1.15 on 2026-04-30 07:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('MERCADOPAGO', 'Mercado Pago')], max_length=15)),
                ('submetodo', models.CharField(choices=[('NINGUNO', 'N/A'), ('TARJETA', 'Tarjeta'), ('YAPE', 'Yape'), ('PAGOEFECTIVO', 'PagoEfectivo'), ('BILLETERA_MP', 'Billetera MP')], default='NINGUNO', max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Debe coincidir con boleta.total al momento del cobro.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('monto_recibido', models.DecimalField(blank=True, decimal_places=2, help_text='Solo EFECTIVO. Monto que entrego el cliente en cash.', max_digits=10, null=True)),
                ('vuelto', models.DecimalField(blank=True, decimal_places=2, help_text='Solo EFECTIVO. Calculado: monto_recibido - monto.', max_digits=10, null=True)),
                ('referencia_mp', models.CharField(blank=True, db_index=True, help_text='ID de transaccion devuelto por Mercado Pago.', max_length=100)),
                ('respuesta_gateway', models.JSONField(blank=True, default=dict, help_text='Respuesta cruda del gateway, para auditoria/debug.')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
    ]
