# Generated by Django 5.1.15 on 2026-04-30 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='boleta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='ventas.boleta'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia_mp', ''), _negated=True), fields=('referencia_mp',), name='pago_referencia_mp_unica_cuando_existe'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('metodo', 'EFECTIVO'), ('submetodo', 'NINGUNO')), models.Q(('metodo', 'MERCADOPAGO'), models.Q(('submetodo', 'NINGUNO'), _negated=True)), _connector='OR'), name='pago_submetodo_consistente'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='pago_monto_positivo'),
        ),
    ]
