# Generated by Django 5.1.15 on 2026-04-30 07:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('turnos', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoPersistente',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='carrito', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrito persistente',
                'verbose_name_plural': 'Carritos persistentes',
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('BOLETA', 'Boleta'), ('TICKET', 'Ticket')], default='BOLETA', max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('igv', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('descuento_global', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=15)),
                ('anulada_fecha', models.DateTimeField(blank=True, null=True)),
                ('anulada_motivo', models.CharField(blank=True, max_length=255)),
                ('pdf_url', models.FileField(blank=True, null=True, upload_to='boletas/')),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletas_anuladas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletas_cliente', to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletas', to='turnos.turnocaja')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletas_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio del producto al momento de la venta (snapshot, no cambia).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Calculado: cantidad * precio_unitario - descuento_aplicado', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.boleta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Detalle de boleta',
                'verbose_name_plural': 'Detalles de boleta',
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('agregado', models.DateTimeField(auto_now_add=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.carritopersistente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Item de carrito',
                'verbose_name_plural': 'Items de carrito',
                'ordering': ['-agregado'],
            },
        ),
        migrations.AddIndex(
            model_name='boleta',
            index=models.Index(fields=['estado', 'fecha'], name='boleta_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='boleta',
            index=models.Index(fields=['cliente', '-fecha'], name='boleta_cliente_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='boleta',
            index=models.Index(fields=['turno', 'estado'], name='boleta_turno_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='boleta',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='boleta_total_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='boleta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'ANULADA'), _negated=True), models.Q(('estado', 'ANULADA'), ('anulada_fecha__isnull', False), ('anulada_por__isnull', False)), _connector='OR'), name='boleta_anulacion_consistente'),
        ),
        migrations.AddConstraint(
            model_name='detalleboleta',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 1)), name='detalle_cantidad_minima'),
        ),
        migrations.AddConstraint(
            model_name='detalleboleta',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='detalle_subtotal_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='itemcarrito',
            constraint=models.UniqueConstraint(fields=('carrito', 'producto'), name='item_carrito_producto_unico'),
        ),
        migrations.AddConstraint(
            model_name='itemcarrito',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 1)), name='item_cantidad_minima'),
        ),
    ]
