# Generated by Django 5.1.15 on 2026-04-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('STOCK_BAJO', 'Stock bajo'), ('STOCK_AGOTADO', 'Stock agotado'), ('VENCIMIENTO_CERCANO', 'Proximo a vencer'), ('SISTEMA', 'Sistema'), ('PAGO_FALLIDO', 'Pago fallido')], max_length=25)),
                ('nivel', models.CharField(choices=[('INFO', 'Info'), ('ADVERTENCIA', 'Advertencia'), ('CRITICO', 'Critico')], default='INFO', max_length=15)),
                ('mensaje', models.CharField(max_length=500)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha'],
            },
        ),
    ]
