# Generated by Django 5.1.15 on 2026-04-30 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alertas', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='productos.producto'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(condition=models.Q(('leida', False)), fields=['-fecha'], name='alerta_no_leidas_idx'),
        ),
    ]
