# Generated by Django 5.1.15 on 2026-04-30 07:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apertura_fecha', models.DateTimeField(auto_now_add=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, help_text='Efectivo con el que abre la caja (cambio inicial).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cierre_fecha', models.DateTimeField(blank=True, null=True)),
                ('monto_contado_cierre', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo contado fisicamente al cerrar.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Turno de caja',
                'verbose_name_plural': 'Turnos de caja',
                'ordering': ['-apertura_fecha'],
            },
        ),
    ]
