# Generated by Django 5.1.15 on 2026-04-30 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turnocaja',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='turnocaja',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTO')), fields=('vendedor',), name='turno_unico_abierto_por_vendedor'),
        ),
        migrations.AddConstraint(
            model_name='turnocaja',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cierre_fecha__isnull', True), ('estado', 'ABIERTO'), ('monto_contado_cierre__isnull', True)), models.Q(('cierre_fecha__isnull', False), ('estado', 'CERRADO'), ('monto_contado_cierre__isnull', False)), _connector='OR'), name='turno_cierre_consistente'),
        ),
    ]
