# Generated by Django 5.1.15 on 2026-04-30 07:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_icono', models.ImageField(blank=True, null=True, upload_to='categorias/')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PORCENTAJE', '% descuento'), ('MONTO_FIJO', 'Monto fijo S/'), ('NXM', 'N por M (2x1, 3x2)')], max_length=15)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Para PORCENTAJE (0-100) o MONTO_FIJO (>0). Vacio si tipo=NXM.', max_digits=6, null=True)),
                ('lleva_n', models.IntegerField(blank=True, help_text='Solo NXM: cantidad que lleva el cliente', null=True, validators=[django.core.validators.MinValueValidator(2)])),
                ('paga_m', models.IntegerField(blank=True, help_text='Solo NXM: cantidad que paga (debe ser < lleva_n)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='FotoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos_fotos/')),
                ('orden', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Foto de producto',
                'verbose_name_plural': 'Fotos de productos',
                'ordering': ['orden', 'creado'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Historial de precio',
                'verbose_name_plural': 'Historial de precios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida (venta)'), ('AJUSTE', 'Ajuste manual'), ('ANULACION', 'Devolucion por anulacion')], max_length=15)),
                ('cantidad', models.IntegerField(help_text='Magnitud del movimiento. Solo AJUSTE puede ser negativo.')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.CharField(help_text='Convencion: <CATEGORIA>-<correlativo> (ej: BEB-001, CON-001). Debe coincidir EXACTAMENTE con el prefijo del id_chroma en ChromaDB (el ia-service hace split("_")[0] para extraerlo).', max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_\\-]+$', 'SKU solo permite letras (A-Z), numeros, guion y guion bajo. Sin Ñ, acentos ni espacios.')])),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio INCLUYE IGV 18%', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_minimo', models.IntegerField(default=5, help_text='Cuando stock <= stock_minimo se genera alerta', validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('contador_ventas', models.IntegerField(default=0, help_text='Total unidades vendidas. Se actualiza por signal al pagar boleta.', validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^(10|15|17|20)\\d{9}$', 'RUC peruano: 11 digitos, empieza con 10, 15, 17 o 20')], verbose_name='RUC')),
                ('razon_social', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, help_text='Puede ser fijo, celular o internacional', max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{6,15}$', 'Telefono entre 6 y 15 digitos')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('persona_contacto', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('texto', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resena',
                'verbose_name_plural': 'Resenas',
                'ordering': ['-fecha'],
            },
        ),
    ]
