# Generated by Django 5.1.15 on 2026-04-30 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialprecio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='boleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='ventas.boleta'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='padre',
            field=models.ForeignKey(blank=True, help_text='Si es variante, apunta al producto padre', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='historialprecio',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='fotoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_por', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='descuento',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.proveedor'),
        ),
        migrations.AddField(
            model_name='resena',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas_escritas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resena',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='productos.producto'),
        ),
        migrations.AddIndex(
            model_name='movimientostock',
            index=models.Index(fields=['producto', '-fecha'], name='movstock_prod_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='historialprecio',
            index=models.Index(fields=['producto', '-fecha'], name='historial_prod_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorito',
            constraint=models.UniqueConstraint(fields=('cliente', 'producto'), name='favorito_cliente_producto_unique'),
        ),
        migrations.AddConstraint(
            model_name='descuento',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='descuento_fechas_validas'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'padre'], name='prod_activo_padre_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(condition=models.Q(('fecha_vencimiento__isnull', False)), fields=['fecha_vencimiento'], name='prod_vencimiento_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['-contador_ventas'], name='prod_top_ventas_idx'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gt', 0)), name='producto_precio_positivo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='producto_stock_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='resena',
            index=models.Index(fields=['producto', '-fecha'], name='resena_prod_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='resena',
            constraint=models.UniqueConstraint(fields=('producto', 'cliente'), name='resena_producto_cliente_unique'),
        ),
        migrations.AddConstraint(
            model_name='resena',
            constraint=models.CheckConstraint(condition=models.Q(('estrellas__gte', 1), ('estrellas__lte', 5)), name='resena_estrellas_1_5'),
        ),
    ]
