# Generated by Django 5.1.15 on 2026-06-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resena',
        ),
    ]
